### ISSUE TITLE
The cursor is getting misaligned

### ISSUE THREAD

**Issue by sommelon** [Jeusto/warm-up-vscode#4] opened 2021-09-14 17:15 UTC
The cursor gets further from the current letter, the longer I type on one line
![image](https://user-images.githubusercontent.com/57922071/133303402-dad9be5b-ea7d-4243-b3bc-414d8667d2c9.png)
The next letter on the picture is `a` in `all()`, but the cursor is near the parentheses.

**Comment by dankilman** [comment] 2022-01-12 23:40
I suspect this magic number is the culprit
https://github.com/Jeusto/vscode-typing-test/blob/2a953099f93b115780df66861a30287113afd8ff/webview/main.js#L823

**Comment by dankilman** [comment] 2022-01-12 23:59
I just confirmed this by changing the value locally in `~/.vscode/extensions/jeusto.warm-up-typing-test-1.0.0/media/main.min.js` to `0.5` (after searching for the string `cursorWidth=`.
I played with this number locally and `0.5` seems to work very well for me. I'm not sure how to generically get this number though. Perhaps worth exposing this a configuration option with some few know to work well numbers?
Of course, making it work out of the box would be best, but at the very least this would allow some less hacky way to workaround this issue

**Comment by Jeusto** [comment] 2022-01-13 02:33
> I just confirmed this by changing the value locally in `~/.vscode/extensions/jeusto.warm-up-typing-test-1.0.0/media/main.min.js` to `0.5` (after searching for the string `cursorWidth=`. I played with this number locally and `0.5` seems to work very well for me. I'm not sure how to generically get this number though. Perhaps worth exposing this a configuration option with some few know to work well numbers? Of course, making it work out of the box would be best, but at the very least this would allow some less hacky way to workaround this issue

Yeah, it's definitely due to that arbitrary value. I kind of forgot about this but I'll try to look into it. The problem is I can't figure it how to calculate the correct offset. I'm able to get user's current font size. I thought the offset would be "width of 1 character + letter-spacing" but it's not, If you have any idea let me know. If I can't figure it out, l'll change the arbitrary multiplier to a value that's good for everyone.

**Comment by dankilman** [comment] 2022-01-13 08:15
I certainly don't know how calculate this value correctly.
If you don't find how to do that however, I don't think you will find a single number that works for all. I believe `.601` works well for you, otherwise it wouldn't be in the code. `0.5` works well for me. It probably won't for you.
This is why I suggested making this value configurable in the settings. Not the best solution, but with a proper documentation there, people will at least be able to tweak it a little until they find a number that works for them.
I find the other aspects of this extension very useful and aesthetic so nice job there!

**Comment by Jeusto** [comment] 2022-01-13 11:06
Thanks! I'll see what I can do

**Comment by Jeusto** [comment] 2022-07-14 20:46
Late response, but this got fixed with #7

**Closed as completed** 2022-07-14 20:46 UTC
Labels: bug
